apiVersion: v1
kind: Service
metadata:
  name: openssh-test
spec:
  selector:
    app: openssh-test
  clusterIP: None
  ports:
  - name: ssh
    port: 22
---
apiVersion: v1
kind: Pod
metadata:
  name: openssh-server
  labels:
    app: openssh-test
spec:
  hostname: openssh-server
  subdomain: openssh-test
  containers:
  - name: openssh
    image: rongou/openssh
    command: ["/bin/sh"]
    args: ["-c", "ssh-keygen -A && /usr/sbin/sshd -o StrictModes=no -D -e"]
    volumeMounts:
    - name: ssh-keys
      mountPath: "/root/.ssh"
  volumes:
  - name: ssh-keys
    secret:
      secretName: ssh-keys
      defaultMode: 256
      items:
      - key: id_ed25519.pub
        path: authorized_keys
---
apiVersion: batch/v1
kind: Job
metadata:
  name: openssh-client
spec:
  template:
    spec:
      containers:
      - name: openssh
        image: rongou/openssh
        command: ["ssh"]
        args: [
          "openssh-server.openssh-test",
          "-o",
          "StrictHostKeyChecking=no",
          "hostname"
        ]
        volumeMounts:
        - name: ssh-keys
          mountPath: "/root/.ssh"
      volumes:
      - name: ssh-keys
        secret:
          secretName: ssh-keys
          defaultMode: 256
      restartPolicy: Never
